install:
  encrypted_partitions:
  - COS_PERSISTENT
  auto: true
  restart: true
  device: "/dev/sda"

hostname: metal-{{ trunc 4 .MachineID }}
users:
- name: kairos
  passwd: kairos
  groups:
  - admin
k3s:
  enabled: true
kcrypt:
  remote_unlock:
    edgevpn_token: b3RwOgogIGRodDoKICAgIGludGVydmFsOiA5MjIzMzcyMDM2ODU0Nzc1ODA3CiAgICBrZXk6IDN6cWpYeDBpNjZaZ3p6a2NQUHcxc1laWlNEUzZqUUE5eW5EdXNySXNieWcKICAgIGxlbmd0aDogNDMKICBjcnlwdG86CiAgICBpbnRlcnZhbDogOTIyMzM3MjAzNjg1NDc3NTgwNwogICAga2V5OiBhaEdSdDN4bjdMZHlBeEJDekhLYmJzZzg1dmZkTHl0Zm9yS2VOWjFzOGlhCiAgICBsZW5ndGg6IDQzCnJvb206IGQ1TXdIc3ZTbUpmdDl6Z0M0ZjBQeDBibnB6OWZUQ05JSFJoRE1KSHBhMlMKcmVuZGV6dm91czogZTk5ZW5sZ0JsWEl1c1B6bEJGSlZKSmVRVlE2ckNsTURJZEtkYXFVdXlncAptZG5zOiA4UWtZb29McWsyYURGSE02R3o5d3N2dEM2U1kxNWxnVlZBYlVOZ015RjlFCm1heF9tZXNzYWdlX3NpemU6IDIwOTcxNTIwCg==
    # Public Key of the client
    public_key: |
       -----BEGIN PUBLIC KEY-----
       MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr9Pma8g7WxE9RQzH/TWk
       2fUBDbrJFBqZzkyLUgpIE6YBo2FkUDILem+M3w6SsHXbLa7hukPiAcOTTcvTiOdG
       wmb855dEyR440Pn4fodR9SRN/QyOpRGyCWBRdR7cRdSdU69iDin/XkyfZOjGcPGu
       +fbvxl2LiEjvK3Z2oqAD0kKEwF/ShZmnctG3WY422OeBralVGvI2jtB1t3i9bRDo
       uZThGoAT9DIT6uXWZL1AN5CxjwGUS1HdHurLTGXqGEMbnuW4thSSIYHCSNEEuDrm
       iltSa4epycmSh/c3RpngLmM34T/rrRrYUIH9GoG5OgKhJX/o2XKPcdEooIFY6LGV
       NwIDAQAB
       -----END PUBLIC KEY-----
    # Private Key of Droplet
    private_key: |
       -----BEGIN PRIVATE KEY-----
       MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCqK2hsTTEWSlb2
       lFNhnVJ6Rr4nSqnRp5ZSlHncp+wC8Y/0LLZeTRMsfLSNwOptQkG26ELvTcbLy26F
       lo0jI7D/cpMlApt2yKzwczB1d4Ph9L6ahPsvDhISu+iHbK1fou8WmrPw63l+UXBD
       lzU+mqyB5d3GxK3ndg4+K853zkcVLOmCBv4uuC/T3gnFdLL09ZDNdVV4RQ6qQMU3
       F2XW/BSbqD9e/jvzVp0vh3CnJhQWppzAm3RoY/d7ZkC5DHCzc0YTIkFEsxLc4skj
       CEv7gczw+wYWNdVdkq1C8DzizaBiAuCT+4kXiel6SpqjtMXDozw7EhUFlA48dhYC
       Di7iX2vBAgMBAAECggEAT2GoeL0ZpPhQ0P4oV2T4UKonklS2G2M+MI+quVBsPINL
       T/B7sknqI9qYr3fK4+UAmr6GWvPBRNhFWnP8quO/caqVEbLBqwu6AQD7HhD+qK1v
       LM3UDwNVUv/tXR9JUU/EkJriTgTKzC5ZXG5xHB8zUfVVG6AsL8lWo5Hz4teLOUjT
       IVtQSmsUUZNKI96kfCUdWJAHtp/qdz+TnkAcEQLUp6G16dJ7G8dl+JQDnxPn7why
       VwhDLqfD/VDeQHHav7KKzx+p64rRfOgM+p6aT8NiBFOo8VNWYjhUIAKGbW34tOjb
       rIyrbeAhF+w9/skgHqmhcXPLzXL8KzNwOLo8515DsQKBgQDdizBz7ysNZ1HRweDF
       BhCZNbq3ufYClpM4YeFqgq9sSlUTDT0Hkw2frNLhSTVGkGaPyDpiwNZz17T+9lie
       QMTiap3ISD6LqTKzcnOcLGP6PhJAQyJawI7riUdFdHbSEOZymQOlhw4WIZsahiD1
       ADLuFyq3r82ysnXcWt6ZgcTrDwKBgQDEor7yKvUUQBHumcLz+O3uZq5jaCnb4o6+
       lzbmc+TpE2gpTwnQNUHGNgTyFVyQRYBzEQJtih6oeXteFglOqrUAEIgDqS5hsK1b
       Ghe10Xr9ioAofdz8SrILJI2MJdpsFhSNsCNmEmnQZgFYbrV8oGN50zRkUzS1hWHE
       QLR6ENN8LwKBgGhwSGwu8H3GGjUnD73xyPtg79/S451+vHJU+j4K04XaWNa9Y+rh
       MQf4IgWgTGQyiJb5jkSlobNEmgejvE0GPYp7NlyHaizOm58qskOKTatXfaUbwONF
       aVqyAY5FhAote2XEqopq64IVX5gWaQz2hgvlkfa8At1d8d/qWovFOD6TAoGAFTKa
       NQ8Odo1loXwv+Q8Xz0CAgjTjdlHZI5C3mWZbAglWjEV6AFkNaym9pL9KyD7F1yG5
       Ske+gFkARKdJf5KFiqk9kG93kY5zUcPhVHdts9FveW4AGa6PvQXGwJoADvDebFvV
       pRZNE+s7L+ZXaET+FE8BceNKZlsnq/lxu0r/EX8CgYAdCXd8Z7Cax8DKQGNh/8Ey
       36A8a8IRP+huJ6pVe0f3Zol/C18qC7pXUwdGHujgZhwfXhEfybWvQnYV2SMS2xlZ
       bysOC8OWjs8YvNXkwmljpjpLGM0DijchlYyqpRTvhKU81r5brZrtqnKBcvYUmAX9
       BiUnQOy/dsZQJp4pcd4y2A==
       -----END PRIVATE KEY-----
