install:
  encrypted_partitions:
  - COS_PERSISTENT
  auto: true
  restart: true
  device: "/dev/sda"

hostname: metal-{{ trunc 4 .MachineID }}
users:
- name: kairos
  # Change to your pass here
  passwd: kairos
  groups:
  - admin
k3s:
  enabled: true
