install:
  encrypted_partitions:
  - COS_PERSISTENT
  grub_options:
    extra_cmdline: "rd.neednet=1"
  auto: true
  restart: true
  device: "/dev/sda"

hostname: metal-{{ trunc 4 .MachineID }}
users:
- name: kairos
  passwd: kairos
  groups:
  - admin
k3s:
  enabled: true
kcrypt:
  remote_unlock:
    edgevpn_token: b3RwOgogIGRodDoKICAgIGludGVydmFsOiA5MjIzMzcyMDM2ODU0Nzc1ODA3CiAgICBrZXk6IDlYSndzTFRLQ1Nad2d3VEFuYkVDSGNWQ1pxcmRyekpHME56Wm1sbVI1elIKICAgIGxlbmd0aDogNDMKICBjcnlwdG86CiAgICBpbnRlcnZhbDogOTIyMzM3MjAzNjg1NDc3NTgwNwogICAga2V5OiBydEdESThCNDlGa1pUbnZkZHJzdHY5T0hSNXFnb2M3QnhjcGJ3WDFoU0NzCiAgICBsZW5ndGg6IDQzCnJvb206IGJCTUZUWjhmSkV1c2twOUJHMXNOS1pmMXhvRXBObjhQQjY1VWlQcWIzdHcKcmVuZGV6dm91czogVGNCakJId0Y3NzhNQ0JYN2hxbDRvdVluMkNEdkY1Yml0RWNab2tYcnRDWgptZG5zOiB1ZWtxSDVlbFk4Q1dpWDdiMlFLQWhQVjVsNFB2TTNOQjhjaFR1NjVMazBTCm1heF9tZXNzYWdlX3NpemU6IDIwOTcxNTIwCg==
    # Public Key of the client
    public_key: |
       -----BEGIN PUBLIC KEY-----
       MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAszqGnU10j67JdND+8ook
       SUw9OdCZhmQKFTW7eWrLz9hVS8TwTNTXGKrZXez2tppiQ4V5+yygVr2Xhqd7JmiQ
       B7QsjqVDv5GqUBLxHDX8b3B70H9kz/4FmsHvqtI/uxe4bjI6Wcu506SfXSOxQcvH
       lZSZzzeLKN8rPKl79tNoOE8+nbeF+8C5SeER0HoTXj1RO4o8MJ6s3gGIpit/B096
       OUyTwwg4rRm+lj5/vDKygP+IwCupMZPMixCTYyPHWhaWgFHmaGxRRET6MZxfXulG
       T4RzLPpovimkRGQ/arZh/S0VkgQqCm/qmT2/7pKHRnCzii5DSWtKmaZK0ys9akhY
       4wIDAQAB
       -----END PUBLIC KEY-----
    # Private Key of Droplet
    private_key: |
       -----BEGIN PRIVATE KEY-----
       MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDyWxBOj/lx7YsN
       qdY/EtYIwvJeT2C7W93EWA+8/tuI6FMdRjqk4+K4GC6YoH8KX7Jj7VezamrtdcYN
       wxOODtddDf2OZI6JohtMXwj5dFqGRRt2DzIATSpasH+pYUkEPTvw8NGPZ9TMeZFQ
       jAv/7weCQNfSPoDS+fRuKvb3TGeZLSFVSF2ZPie3yL63BmRWPYuFB+DXRuO9v1mO
       aDSWtDy4JNZ4hzWkPSh8beaGSuPahmrWo0BRG9mp+GfAUo55LKgOakHlbGdICjLb
       q/mbBCqiI7mHbKROfBGIVt0Ulx/8ypF4cAvqUAt5HgF3ha86KbG5K78Gouhk0hJX
       jZPH22uZAgMBAAECggEAL7U3Z4+19fRh7CWjtDTcB0uA9InBrAAwjqcbKgQtaSz6
       t4eMocruZXj1Kzxk5cDi2ALvwbTQKcCGZU0ie1N2l63aXP50hKlxoD4RATIjY80U
       08+38xE9pi6aYthwzDHVq99sEUPKQxonPejjr9T48G4dThjZuS5VLJ6ukQ3sUt2K
       XXbdedWwypMI11gZ2UwGS13BY7opuKoiKWBRT8pu3HRiKoKLCPtAnLiXySUICUVk
       zV7Tt6fCCUZ23TEX83HyBLoDh1s0biqkc78D70R7RuQc//KSgh/g2rSDc12SAoIM
       pGSblmvezYQaCzL5EGEESb3Ijyr3uoffx7UUYuH7NQKBgQD0QPVYsbz2vkomtuPi
       UJR705691KRvKXzQI0g3YSdiNe0jlDU4ijYJb1oyLU2rXhYSy7Yag8pdR8CU0lPS
       ztHpTf+ekHK7wciCm6LsKZUSqqXWMRxwPpMgna3IP+ASuTEUjMuTcgchKNP734vY
       8Panptn/4a17AwnRiG5G98Vd+wKBgQD+Ar0LM1zdjC44Ooj+zzt+eJkVVB7dYCx+
       g6lpNvvnfQ2tjl1Ezi44jOd7uD2/dH4xc6/ou/c5aVT4noDNyqlgGuHQAxEhEctK
       U5yOFRghAgpr29QNykqhc7Yx3T9PJIYJ1vXtn/Zr9n/iuQjkmxyGDt16Y0vY8Xnx
       4VdgLkaMewKBgETBRE8DOT37ssPTF7LNG/7/QuAMy3y/IPM1+04bewqaQ3aQcarI
       vQ1K2wjk18g1Y+FGlqxADObVG9DIo+/jaBNUcXAhGSrhEaAyT1pLGjt27detW2P9
       OU0lFZYY5OpgVwCB4YxPvNIIvCNaefNHYScwQI1W6Y6G/GyPCvvPIy+hAoGBAPG9
       Y3KccD384iPrOWPfj4xec7pDs5gVpmLFJN6YUIbPkcvh2EvaOUzidI9fGYzy7gJc
       SkahVLiT0SVHm+e+fxGSo+OWd5/UUnerOSxTUQJg8dAShy6UnhAnknbETDMi3FnS
       9Xwvp5K6Jp18YcVHBY9j6E5I3+9YaSjUv5YulD+vAoGBAMhPmzLXTxQdaJKfNnlE
       T+OCv8m/jooIwsxP+7MVE56gvqoDIO94E3Tc9Kl0CwFHMk//J/WHZTd4dKdWBwmw
       LFRVQKRY8L8Oo4F/G8Fc1dH9C3IpdpPNSnfnxAmCKo0Qtz8tpCe2Si8pLkZSJubP
       80Ngnz1wTwBMoVYUoRV+Xk5p
       -----END PRIVATE KEY-----
