name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - client/
      - README.md
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
  actions: read
  packages: write
  security-events: write
  models: none
jobs:
  setup-version:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
        id: tag
  build-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'
      - name: Install dependencies
        run: mkdir build && go mod download
      - name: Build mac
        run: GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -v -o ./build/re-unlock-cli_mac ./client/main.go
      - name: Build linux amd64
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v -o ./build/re-unlock-cli_linux-amd64 ./client/main.go
      - name: Build linux arm64
        run: GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -v -o ./build/re-unlock-cli_linux-arm64 ./client/main.go
      - name: Build linux arm (32-Bit)
        run: GOOS=linux GOARCH=arm CGO_ENABLED=0 go build -v -o ./build/re-unlock-cli_linux-arm ./client/main.go
      - uses: actions/upload-artifact@v4
        with:
          path: ./build/
          name: re-unlock-cli.zip
  build-droplet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'
      - name: Install dependencies
        run: mkdir build && go mod download
      - name: Build linux amd64
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v -o ./build/re-unlock-droplet_linux-amd64 ./droplet/main.go
      - name: Build linux arm64
        run: GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -v -o ./build/re-unlock-droplet_linux-arm64 ./droplet/main.go
      - uses: actions/upload-artifact@v4
        with:
          path: ./build/
          name: re-unlock-droplet.zip
  nix-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - name: Check flake
        run: nix flake check --no-build
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    needs: ["build-cli", "build-droplet", "setup-version", "nix-check"]
    steps:
      - run: mkdir /tmp/artifacts
      - uses: actions/download-artifact@v5
        with:
          pattern: "*.zip"
          path: /tmp/artifacts
      - run: |
          for zipfile in /tmp/artifacts/*.zip; do
              if [ -f "$zipfile" ]; then
                  unzip -o "$zipfile" -d /tmp/artifacts/
              fi
          done
      - run: |
          arts=$(python3 -c 'import os
          res = []
          for root, dirs, files in os.walk("/tmp/artifacts"):
              for name in files:
                  if name.startswith("re-unlock-"):
                      res.append(os.path.join(root, name))
          print(str.join(",", res))')
          echo "artifacts=${arts}" >> ""$GITHUB_OUTPUT""
        id: artifacts
      - uses: ncipollo/release-action@v1.20.0
        with:
          artifacts: ${{ steps.artifacts.outputs.artifacts }}
          tag: ${{ needs.setup-version.outputs.version }}
          skipIfReleaseExists: true
